[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
version = "1.0.0"
name = "precision_track_re_identification"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies=[
          'timm==1.0.27',
          'numpy==2.2.4',
          'pandas==2.2.3',
          'tqdm==4.67.1',
          'opencv-python==4.11.0.86',
          'Pillow==11.2.1',
          'scikit-learn==1.6.1',
          'pycocotools==2.0.8',
          'tensorboard==2.19.0',
          'pytorch_metric_learning==2.8.1',
          'transformers==4.51.3',
          'wildlife-datasets==1.0.7',
          'kornia==0.8.0',
          'onnx==1.17.0',
          'onnxconverter-common==1.14.0',
          'plotext==5.3.2',
          'addict==2.4.0'
]

[project.optional-dependencies]
cuda = [
    "pycuda==2025.1.1",
    "tensorrt==10.11.0.33",
    "onnxruntime-gpu[cuda,cudnn]==1.22.0",
]

[project.urls]
"Homepage" = "https://github.com/VincentCoulombe/precision_track-ReID"
"Documentation" = "https://wildlifedatasets.github.io/wildlife-tools/"


[tool.setuptools]
packages = [
  "wildlife_tools",
  "wildlife_tools.data",
  "wildlife_tools.inference",
  "wildlife_tools.features",
  "wildlife_tools.similarity",
  "wildlife_tools.similarity.pairwise",
  "wildlife_tools.train",
  "wildlife_tools.fork_additions",
]

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
